[package]
name = "nft-trading-board"
version = "1.0.0"
authors = []

[addresses]
MyModule="0xfd3bacb6d0f13d8e5492d8b75d72496372410dae74652aba309d545d8676b6d9"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
